// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH A MODIWL
// This file is automatically generated. DO NOT EDIT

import type { AppOverview } from "../../../src/types/app-overview";
import type { DestinationInput } from "../../../src/types/destination";
import type { ExecutionSummary } from "../../../src/types/execution";
import type { ActiveLiveNowSession } from "../../../src/types/live-now-recovery";
import type { LogEntry } from "../../../src/types/log-entry";
import type { AnnouncementInput, PreviewItem } from "../../../src/types/preview";
import type { AppSettings } from "../../../src/types/settings";

export function ClearPendingLiveNowSession(arg1: string): Promise<ExecutionResult>;
export function DeleteDestination(arg1: string): Promise<void>;
export function DryRun(arg1: AnnouncementInput): Promise<ExecutionSummary>;
export function EndStream(): Promise<ExecutionSummary>;
export function ForceGoLive(arg1: AnnouncementInput): Promise<ExecutionSummary>;
export function GeneratePreview(arg1: AnnouncementInput): Promise<PreviewItem[]>;
export function GetDiagnostics(): Promise<string>;
export function GetLogs(): Promise<LogEntry[]>;
export function GetOverview(): Promise<AppOverview>;
export function GetSettings(): Promise<AppSettings>;
export function GoLive(arg1: AnnouncementInput): Promise<ExecutionSummary>;
export function ListPendingLiveNowSessions(): Promise<Array<ActiveLiveNowSession>>;
export function ListDestinations(): Promise<DestinationInput[]>;
export function SaveDestination(arg1: DestinationInput): Promise<DestinationInput>;
export function SaveSettings(arg1: AppSettings): Promise<AppSettings>;
