// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function ClearPendingLiveNowSession(arg1:string):Promise<domain.ExecutionResult>;

export function DeleteDestination(arg1:string):Promise<void>;

export function DryRun(arg1:domain.Announcement):Promise<domain.ExecutionSummary>;

export function EndStream():Promise<domain.ExecutionSummary>;

export function ForceGoLive(arg1:domain.Announcement):Promise<domain.ExecutionSummary>;

export function GeneratePreview(arg1:domain.Announcement):Promise<Array<domain.PreviewItem>>;

export function GetDiagnostics():Promise<string>;

export function GetLogs():Promise<Array<domain.LogEntry>>;

export function GetSettings():Promise<domain.AppSettings>;

export function GoLive(arg1:domain.Announcement):Promise<domain.ExecutionSummary>;

export function ListDestinations():Promise<Array<domain.Destination>>;

export function ListPendingLiveNowSessions():Promise<Array<domain.ActiveLiveNowSession>>;

export function SaveDestination(arg1:domain.Destination):Promise<domain.Destination>;

export function SaveSettings(arg1:domain.AppSettings):Promise<domain.AppSettings>;

export function TestDestinationConnection(arg1:domain.Destination):Promise<domain.CredentialCheckResult>;
