// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearPendingLiveNowSession(arg1) {
  return window['go']['main']['App']['ClearPendingLiveNowSession'](arg1);
}

export function DeleteDestination(arg1) {
  return window['go']['main']['App']['DeleteDestination'](arg1);
}

export function EndStream(arg1) {
  return window['go']['main']['App']['EndStream'](arg1);
}

export function ForceGoLive(arg1) {
  return window['go']['main']['App']['ForceGoLive'](arg1);
}

export function GeneratePreview(arg1) {
  return window['go']['main']['App']['GeneratePreview'](arg1);
}

export function GetDiagnostics() {
  return window['go']['main']['App']['GetDiagnostics']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GoLive(arg1) {
  return window['go']['main']['App']['GoLive'](arg1);
}

export function ListDestinations() {
  return window['go']['main']['App']['ListDestinations']();
}

export function ListPendingLiveNowSessions() {
  return window['go']['main']['App']['ListPendingLiveNowSessions']();
}

export function SaveDestination(arg1) {
  return window['go']['main']['App']['SaveDestination'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function TestDestinationConnection(arg1) {
  return window['go']['main']['App']['TestDestinationConnection'](arg1);
}
